# Generated by Django 5.1.2 on 2024-11-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BhavanComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('0', 'Block 0'), ('1', 'Block 1'), ('2', 'Block 2'), ('3', 'Block 3'), ('4', 'Block 4'), ('5', 'Block 5'), ('6', 'Block 6'), ('7', 'Block 7'), ('8', 'Block 8'), ('9', 'Block 9'), ('Qtr 75', 'Quarter 75'), ('Qtr 76', 'Quarter 76'), ('Qtr 77', 'Quarter 77'), ('Qtr 78', 'Quarter 78'), ('Qtr 79', 'Quarter 79'), ('Qtr 80', 'Quarter 80'), ('Common Area', 'Common Area'), ('Visitors Room', 'Visitors Room'), ('Mess', 'Mess')], max_length=20, verbose_name='Block/Quarter')),
                ('floor', models.CharField(choices=[('0', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], max_length=1, verbose_name='Floor')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room Number')),
                ('toilet', models.CharField(choices=[('T1', 'Toilet 1'), ('T2', 'Toilet 2'), ('T3', 'Toilet 3'), ('T4', 'Toilet 4'), ('T5', 'Toilet 5'), ('T6', 'Toilet 6'), ('T7', 'Toilet 7'), ('T8', 'Toilet 8'), ('T9', 'Toilet 9'), ('T10', 'Toilet 10'), ('T11', 'Toilet 11'), ('T12', 'Toilet 12')], max_length=3, verbose_name='Toilet')),
                ('request_related', models.CharField(choices=[('Carpenter', 'Carpenter'), ('Sweeper', 'Sweeper'), ('Gardener', 'Gardener'), ('Plumber', 'Plumber'), ('RO Person', 'RO Person'), ('Electrician', 'Electrician'), ('Mason', 'Mason'), ('Painter', 'Painter'), ('Worker', 'Worker')], max_length=20, verbose_name='Request Related To')),
                ('subcategory', models.CharField(max_length=50, verbose_name='Subcategory')),
                ('complaint_description', models.TextField(blank=True, null=True, verbose_name='Complaint Description')),
                ('complaint_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('To EMS', 'To EMS'), ('Resolved', 'Resolved')], default='Pending', max_length=20, verbose_name='Complaint Status')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported Date and Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Complaint Owner')),
            ],
            options={
                'verbose_name': 'Bhavan Complaint',
                'verbose_name_plural': 'Bhavan Complaints',
                'ordering': ['-reported_at'],
            },
        ),
    ]
