# Generated by Django 5.1.2 on 2024-11-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='toilet',
            field=models.CharField(blank=True, choices=[('T1', 'Toilet 1'), ('T2', 'Toilet 2'), ('T3', 'Toilet 3'), ('T4', 'Toilet 4'), ('T5', 'Toilet 5'), ('T6', 'Toilet 6'), ('T7', 'Toilet 7'), ('T8', 'Toilet 8'), ('T9', 'Toilet 9'), ('T10', 'Toilet 10'), ('T11', 'Toilet 11'), ('T12', 'Toilet 12')], max_length=3, null=True, verbose_name='Toilet'),
        ),
    ]
