# Generated by Django 5.1.2 on 2024-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_bhavancomplaints_toilet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='block',
            field=models.CharField(blank=True, choices=[('0', 'Block 0'), ('1', 'Block 1'), ('2', 'Block 2'), ('3', 'Block 3'), ('4', 'Block 4'), ('5', 'Block 5'), ('6', 'Block 6'), ('7', 'Block 7'), ('8', 'Block 8'), ('9', 'Block 9'), ('Qtr 75', 'Quarter 75'), ('Qtr 76', 'Quarter 76'), ('Qtr 77', 'Quarter 77'), ('Qtr 78', 'Quarter 78'), ('Qtr 79', 'Quarter 79'), ('Qtr 80', 'Quarter 80'), ('Common Area', 'Common Area'), ('Visitors Room', 'Visitors Room'), ('Mess', 'Mess')], max_length=20, null=True, verbose_name='Block/Quarter'),
        ),
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='floor',
            field=models.CharField(blank=True, choices=[('0', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], max_length=1, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='request_related',
            field=models.CharField(blank=True, choices=[('Carpenter', 'Carpenter'), ('Sweeper', 'Sweeper'), ('Gardener', 'Gardener'), ('Plumber', 'Plumber'), ('RO Person', 'RO Person'), ('Electrician', 'Electrician'), ('Mason', 'Mason'), ('Painter', 'Painter'), ('Worker', 'Worker')], max_length=20, null=True, verbose_name='Request Related To'),
        ),
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='bhavancomplaints',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subcategory'),
        ),
    ]
